// run-backtest-hmr-v35.ts -- OLYMPUS HMR v3.5 STRICT vs HYBRID
const fs=require("fs"),path=require("path");
const P={emaF:50,emaS:200,rsi2:2,rsi14:14,adxL:14,adxT:15,adxC:60,regL:120,volL:20,slM:1.5,tp1RR:1.0,trM:2.0,strictG:9,strictS:70,hybG:4,hybS:50,lzK:24,lzLB:100,lzMin:4,mxH:12};
function ema(a,p,i){if(i<1)return a[0];const k=2/(p+1);let e=a[0];for(let j=1;j<=i;j++)e=a[j]*k+e*(1-k);return e;}
function rsi(a,p,i){if(i<p)return 50;let g=0,l=0;for(let j=i-p+1;j<=i;j++){const d=a[j]-a[j-1];if(d>0)g+=d;else l-=d;}return l===0?100:100-100/(1+g/l);}
function linSl(a,p,i){if(i<p-1)return 0;let sx=0,sy=0,xy=0,x2=0;for(let j=0;j<p;j++){sx+=j+1;sy+=a[i-p+1+j];xy+=(j+1)*a[i-p+1+j];x2+=(j+1)*(j+1);}return (p*xy-sx*sy)/(p*x2-sx*sx);}
function adx(h,l,c,i,p){if(i<p*2)return 0;let pD=0,mD=0,tS=0;for(let j=i-p+1;j<=i;j++){const up=h[j]-h[j-1],dn=l[j-1]-l[j];tS+=Math.max(h[j]-l[j],Math.abs(h[j]-c[j-1]),Math.abs(l[j]-c[j-1]));if(up>dn&&up>0)pD+=up;if(dn>up&&dn>0)mD+=dn;}const tA=tS/p;if(tA<=0)return 0;const pI=100*(pD/p)/tA,mI=100*(mD/p)/tA;return(pI+mI)>0?100*Math.abs(pI-mI)/(pI+mI):0;}
function atr(h,l,c,i,p){if(i<p)return 0;let s=0;for(let j=i-p+1;j<=i;j++)s+=Math.max(h[j]-l[j],Math.abs(h[j]-c[j-1]),Math.abs(l[j]-c[j-1]));return s/p;}
function synOHLC(cs){const H=[],L=[],O=[];for(let i=0;i<cs.length;i++){const p=i>0?cs[i-1]:cs[i];const r=Math.abs((cs[i]-p)/Math.max(p,0.01));const tk=0.003+r*1.2;H.push(cs[i]*(1+tk*0.5));L.push(cs[i]*(1-tk*0.5));O.push(p);}return{H,L,O};}
function lzScr(cs,hs,ls,i,ca){if(i<40)return 0;const cR=ca.rsi14[i],cS=ca.sl30[i],cA=ca.adx14[i],cT=ca.atr14[i]/Math.max(cs[i],0.01);const D=[];for(let j=i-P.lzLB;j<i-5;j++){if(j<30)continue;const mR=ca.rsi14[j],mS=ca.sl30[j],mA=ca.adx14[j],mT=ca.atr14[j]/Math.max(cs[j],0.01);const d=Math.log(1+Math.abs(cR-mR))+Math.log(1+Math.abs(cS-mS)*100)+Math.log(1+Math.abs(cA-mA))+Math.log(1+Math.abs(cT-mT)*100);if(j+4<cs.length)D.push({d,y:cs[j+4]-cs[j]});}if(D.length<P.lzK)return 0;D.sort((a,b)=>a.d-b.d);let b=0;for(let n=0;n<P.lzK;n++)if(D[n].y>0)b++;return b-(P.lzK-b);}
function gates(cs,hs,ls,os,i,ca){const e50=ca.ema50[i],e200=ca.ema200[i];const gR=e50>e200?1:0;const sl=ca.sl120[i];const mid=cs[i]+sl*60;let sd=0;for(let j=i-P.regL+1;j<=i;j++)sd+=(cs[j]-mid)*(cs[j]-mid);sd=Math.sqrt(sd/P.regL);const pos=(cs[i]-(mid-sd*2))/Math.max(0.001,sd*4);const gC=(pos>=0.25&&pos<=0.75)?1:0;const r2=ca.rsi2[i];const gRsi=(r2<20||r2>80)?1:0;const a14=ca.adx14[i];const gA=(a14>=P.adxT&&a14<=P.adxC)?1:0;const gLtf=cs[i]>e50?1:0;const gHtf=cs[i]>e200?1:0;const ch=Math.max(0.001,hs[i]-ls[i]);const gStr=(cs[i]-ls[i])/ch>=0.5?1:0;const body=Math.abs(cs[i]-os[i]);const wmax=Math.max(hs[i]-Math.max(cs[i],os[i]),Math.min(cs[i],os[i])-ls[i]);const gW=(wmax/ch)>=0.4&&body<ch*0.5?1:0;const rt=Math.abs((cs[i]-cs[i-1])/Math.max(cs[i-1],0.01));let sr=0;for(let j=i-P.volL+1;j<=i;j++)sr+=Math.abs((cs[j]-cs[j-1])/Math.max(cs[j-1],0.01));const ar=sr/P.volL;const gFl=rt>ar*1.5?1:0;const G=[gR,gC,gRsi,gA,gLtf,gHtf,gStr,gW,gFl];const cnt=G.reduce((a,b)=>a+b,0);const scr=gR*16+gC*10+gRsi*12+gA*12+gLtf*8+gHtf*12+gStr*8+gW*10+gFl*12;return{count:cnt,score:scr,rsi2:r2};}
function shouldEnt(g,lz,side){if(side==="LONG"){return{strict:g.count>=P.strictG&&g.score>=P.strictS&&g.rsi2<30,hybrid:(g.count>=P.strictG&&g.score>=P.strictS&&g.rsi2<30)||(lz>=P.lzMin&&g.count>=P.hybG&&g.score>=P.hybS)};}else{return{strict:g.count>=P.strictG&&g.score>=P.strictS&&g.rsi2>70,hybrid:(g.count>=P.strictG&&g.score>=P.strictS&&g.rsi2>70)||(lz<=-P.lzMin&&g.count>=P.hybG&&g.score>=P.hybS)};}}
function simTr(cs,hs,ls,os,i,side){const e=cs[i];const a=atr(hs,ls,cs,i,14);if(a<=0)return null;const slD=a*P.slM,tpD=slD*P.tp1RR;let sl,tp;if(side==="LONG"){sl=e-slD;tp=e+tpD;}else{sl=e+slD;tp=e-tpD;}let xp=e,exd=i+P.mxH,re="TIMEOUT",hit=false;for(let k=1;k<=P.mxH&&i+k<cs.length;k++){const idx=i+k;if(side==="LONG"){if(ls[idx]<=sl){xp=sl;exd=idx;re="SL";break;}if(hs[idx]>=tp&&!hit)hit=true;if(hit){let hw=e;for(let w=i+1;w<=idx;w++)if(hs[w]>hw)hw=hs[w];if(ls[idx]<=hw-a*P.trM&&k>1){xp=hw-a*P.trM;exd=idx;re="TRAIL";break;}}if(k===P.mxH){xp=cs[Math.min(idx,cs.length-1)];exd=idx;re=hit?"TRAIL_END":"TIMEOUT";}}else{if(hs[idx]>=sl){xp=sl;exd=idx;re="SL";break;}if(ls[idx]<=tp&&!hit)hit=true;if(hit){let lw=e;for(let w=i+1;w<=idx;w++)if(ls[w]<lw)lw=ls[w];if(hs[idx]>=lw+a*P.trM&&k>1){xp=lw+a*P.trM;exd=idx;re="TRAIL";break;}}if(k===P.mxH){xp=cs[Math.min(idx,cs.length-1)];exd=idx;re=hit?"TRAIL_END":"TIMEOUT";}}}const p=(xp-e)/e*(side==="LONG"?1:-1);return{entry:e,exit:xp,side,R:p/(slD/e),days:exd-i,reason:re};}
const cp=path.join(__dirname,"historical_data_daily.csv");const csv=fs.readFileSync(cp,"utf8");const ls=csv.split("\n").filter(l=>l.trim().length>0);const hdr=ls[0].split(",").map(s=>s.trim());const cols={};hdr.forEach((h,i)=>cols[h]=i);const IDX=cols["XNAS.DE"];
const allR=ls.slice(1).map(l=>({date:l.split(",")[0],close:parseFloat(l.split(",")[IDX])})).filter(r=>r.date&&!isNaN(r.close));
const dR=allR.slice(-126);const dates=dR.map(r=>r.date);let cs=dR.map(r=>r.close);for(let i=1;i<cs.length;i++){if(Math.abs(cs[i]-cs[i-1])/cs[i-1]>0.20)cs[i]=cs[i-1];}const{H,L,O}=synOHLC(cs);
console.log("OLYMPUS HMR v3.5 BACKTEST");console.log("Asset: XNAS.DE (Nasdaq-100 ~ QQQ proxy)");console.log("Period:",dates[0],"->",dates[dates.length-1],"("+cs.length+" days, "+(cs.length/21).toFixed(1)+" months)");console.log("Price: "+cs[0].toFixed(2)+" -> "+cs[cs.length-1].toFixed(2));
const ca={ema50:[],ema200:[],rsi2:[],rsi14:[],adx14:[],atr14:[],sl30:[],sl120:[]};for(let i=0;i<cs.length;i++){ca.ema50[i]=ema(cs,50,i);ca.ema200[i]=ema(cs,200,i);ca.rsi2[i]=rsi(cs,2,i);ca.rsi14[i]=rsi(cs,14,i);ca.adx14[i]=adx(H,L,cs,i,14);ca.atr14[i]=atr(H,L,cs,i,14);ca.sl30[i]=linSl(cs,30,i);ca.sl120[i]=linSl(cs,120,i);}
const tr={STRICT:[],HYBRID:[]};for(let i=40;i<cs.length-P.mxH-1;i++){const g=gates(cs,H,L,O,i,ca);const lz=lzScr(cs,H,L,i,ca);const le=shouldEnt(g,lz,"LONG");const se=shouldEnt(g,lz,"SHORT");if(le.strict){const t=simTr(cs,H,L,O,i,"LONG");if(t)tr.STRICT.push(Object.assign({},t,{date:dates[i]}));}if(se.strict){const t=simTr(cs,H,L,O,i,"SHORT");if(t)tr.STRICT.push(Object.assign({},t,{date:dates[i]}));}if(le.hybrid){const t=simTr(cs,H,L,O,i,"LONG");if(t)tr.HYBRID.push(Object.assign({},t,{date:dates[i]}));}if(se.hybrid){const t=simTr(cs,H,L,O,i,"SHORT");if(t)tr.HYBRID.push(Object.assign({},t,{date:dates[i]}));}}
function metrics(arr){const w=arr.filter(t=>t.R>0).length;const tot=arr.reduce((a,t)=>a+t.R,0);const mo=cs.length/21;return{count:arr.length,wins:w,losses:arr.length-w,wr:arr.length?w/arr.length:0,avgR:arr.length?tot/arr.length:0,totalR:tot,tpm:arr.length/mo};}
const m={STRICT:metrics(tr.STRICT),HYBRID:metrics(tr.HYBRID)};
console.log("\n===== COMPARISON =====");console.log("Mode    | Trades |  W/L   |   WR   | AvgR  | TotalR | Trades/Mo");console.log("--------|--------|--------|--------|-------|--------|----------");["STRICT","HYBRID"].forEach(mode=>{const x=m[mode];console.log(mode.padEnd(7)+" | "+String(x.count).padStart(6)+" | "+(String(x.wins)+"/"+String(x.losses)).padStart(6)+" | "+(x.wr*100).toFixed(1).padStart(5)+"% | "+x.avgR.toFixed(2).padStart(5)+" | "+x.totalR.toFixed(1).padStart(6)+" | "+x.tpm.toFixed(1).padStart(5));});
console.log("\n===== TRADE DETAIL =====");["STRICT","HYBRID"].forEach(mode=>{console.log("\n--- "+mode+" ("+tr[mode].length+" trades) ---");console.log("Date   Side  Entry  Exit   R      Days  Reason");tr[mode].forEach(t=>console.log(t.date+"  "+t.side.padEnd(5)+"  "+t.entry.toFixed(2).padStart(6)+"  "+t.exit.toFixed(2).padStart(6)+"  "+t.R.toFixed(2).padStart(6)+"  "+String(t.days).padStart(3)+"   "+t.reason));});
const ratio=m.STRICT.count>0?(m.HYBRID.count/m.STRICT.count):0;console.log("\n===== VERDICT =====");console.log("HYBRID/STRICT ratio = "+ratio.toFixed(2)+"x  (target 2-3x)");console.log("HYBRID WR           = "+(m.HYBRID.wr*100).toFixed(1)+"%  (target >=55%)");console.log("HYBRID AvgR         = "+m.HYBRID.avgR.toFixed(2)+"  STRICT AvgR = "+m.STRICT.avgR.toFixed(2));console.log("Verdict: "+((ratio>=2.0&&m.HYBRID.wr>=0.55&&m.HYBRID.avgR>0)?"CUMPLIDA":"NO CUMPLIDA"));
